load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "helloworld_proto",
    srcs = ["helloworld.proto"],
)

# load("@io_grpc_grpc_java//:java_grpc_library.bzl", "java_grpc_library")

# java_grpc_library(
#     name = "helloworld_java_proto",
#     proto = ":helloworld_proto",
# )